version: "3"

networks:
    db:
    frontend:
    idm_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.18.1.0/24


services:

    # Wirecloud services
    nginx:
        container_name: nginx
        restart: always
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static:/var/www/static:ro
        depends_on:
            - wirecloud
        networks: 
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    postgres:
        container_name: postgres
        restart: always
        image: postgres:latest
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks: 
            - db
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    wirecloud:
        container_name: wirecloud
        restart: always
        image: fiware/wirecloud:latest-composable
        ports:
            - 127.0.0.1:8000:8000
        volumes:
            - ./wirecloud_instance:/opt/wirecloud_instance
            - ./static:/var/www/static
            - ./config-idm.sh:/opt/wirecloud_instance/config-idm.sh
            - ./test.sh:/opt/wirecloud_instance/test.sh
        depends_on:
            - postgres
            - fiware-idm
        networks: 
            - db
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"
        
       
    ngsiproxy:
        container_name: ngsiproxy
        restart: always
        image: fiware/ngsiproxy:latest
        ports:
            - 3010:3000
        networks: 
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    # IdM services
    mysql-idm:
        container_name: mysql-idm
        restart: always
        image: mysql/mysql-server:5.7.21
        ports:
            - 3306:3306
        networks:
            idm_network:
                ipv4_address: 10.18.1.5
        volumes:
            - ./mysql-idm:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=idm
            - MYSQL_ROOT_HOST=10.18.1.6
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    fiware-idm:
        container_name: fiware-idm
        restart: always
        image: fiware/idm
        ports:
            - 3000:3000
            - 443:443
        depends_on:
            - mysql-idm
        networks:
            frontend:
            idm_network:
                ipv4_address: 10.18.1.6
        hostname: fiware-idm
        environment:
            - DATABASE_HOST=mysql-idm
        logging:
            options:
                max-size: "100m"
                max-file: "5"

    ####################
    # Pending PEP Proxy
    ####################

    # Orion services
    mongo:
        container_name: mongo
        restart: always
        image: mongo:3.4
        command: --nojournal
        networks:
            - db
        volumes:
            - ./mongodb:/Users/joudsayedissa/data/db
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    orion:
        container_name: orion
        restart: always
        image: fiware/orion:latest
        ports:
            - 1026:1026
        depends_on:
            - mongo
        networks:
            - frontend
            - db
        hostname: orion
        command: -dbhost mongo -logLevel ERROR
        logging:
            options:
                max-size: "100m"
                max-file: "5"


   # IoT-Agent Ultralight service
    iotagent-ul:
        container_name: iotagent-ul
        restart: always
        image: fiware/iotagent-ul:develop
        ports:
            - "7896:7896"
            - "4041:4041"
        depends_on:
            - orion
        networks:
            - frontend
            - db
        hostname: iotagent-ul
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    # Cygnus service
    cygnus:
        container_name: cygnus
        restart: always
        image: fiware/cygnus-ngsi:latest
        ports:
            - "5050:5050"
        depends_on:
            - mysql-idm
            - orion
        networks:
            - frontend
            - db
        hostname: cygnus
        environment:
            - CYGNUS_MYSQL_USER=root
            - CYGNUS_MYSQL_PASS=mysql
        logging:
            options:
                max-size: "100m"
                max-file: "5"
