version: "3"

networks:
    db:
    frontend:
    idm_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.18.1.0/24


services:

    # Wirecloud services
    nginx:
        container_name: nginx
        hostname: nginx
        restart: always
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static:/var/www/static:ro
        depends_on:
            - wirecloud
        networks: 
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    postgres:
        container_name: postgres
        hostname: postgres
        restart: always
        image: postgres:latest
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks: 
            - db
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    wirecloud:
        container_name: wirecloud
        hostname: wirecloud
        restart: always
        image: fiware/wirecloud:latest-composable
        ports:
            - 127.0.0.1:8000:8000
        volumes:
            - ./wirecloud_instance:/opt/wirecloud_instance
            - ./static:/var/www/static
            - ./config-idm.sh:/opt/wirecloud_instance/config-idm.sh
            - ./config-django-admin.py:/opt/wirecloud_instance/config-django-admin.py
            - ./change-user-permissions.py:/opt/wirecloud_instance/change-user-permissions.py
        depends_on:
            - postgres
            - fiware-idm
        networks: 
            - db
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"
        
       
    ngsiproxy:
        container_name: ngsiproxy
        hostname: ngsiproxy
        image: fiware/ngsiproxy:latest
        ports:
            - 3010:3000
        networks: 
            - frontend
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    # IdM services
    mysql-idm:
        container_name: mysql-idm
        hostname: mysql-idm
        restart: always
        image: mysql/mysql-server:5.7.21
        ports:
            - 3306:3306
        networks:
            idm_network:
                ipv4_address: 10.18.1.5
        volumes:
            - ./mysql-idm:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=idm
            - MYSQL_ROOT_HOST=10.18.1.6
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    fiware-idm:
        container_name: fiware-idm
        hostname: fiware-idm
        restart: always
        image: fiware/idm:latest
        ports:
            - 3000:3000
            - 443:443
        depends_on:
            - mysql-idm
        networks:
            frontend:
            idm_network:
                ipv4_address: 10.18.1.6
        volumes:
            - ./change-config-js.sh:/opt/fiware-idm/change-config-js.sh
        environment:
            - DATABASE_HOST=mysql-idm
        logging:
            options:
                max-size: "100m"
                max-file: "5"

    ####################
    # Pending PEP Proxy
    ####################

    # Orion services
    mongo:
        container_name: mongo
        hostname: mongo
        restart: always
        image: mongo:3.4
        command: --nojournal
        networks:
            - db
        volumes:
            - ./mongodb:/Users/joudsayedissa/data/db
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    orion:
        container_name: orion
        hostname: orion
        restart: always
        image: fiware/orion:latest
        ports:
            - 1026:1026
        depends_on:
            - mongo
        networks:
            - frontend
            - db
        command: -dbhost mongo -logLevel ERROR
        logging:
            options:
                max-size: "100m"
                max-file: "5"


   # IoT-Agent Ultralight service
    iotagent-ul:
        container_name: iotagent-ul
        hostname: iotagent-ul
        restart: always
        image: fiware/iotagent-ul:develop
        ports:
            - "7896:7896"
            - "4041:4041"
        depends_on:
            - orion
        networks:
            - frontend
            - db
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    # Cygnus service
    mysql-db:
        container_name: db-mysql
        hostname: mysql-db
        restart: always
        image: mysql:5.7
        #image: mysql:8.0.11
        ports:
            - "3316:3306"
        networks:
            - db
        volumes:
            # - ./my.cnf:/etc/mysql/conf.d/z_my.cnf"
            - ./mysql-cygnus:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_ROOT_HOST=%"
        logging:
            options:
                max-size: "100m"
                max-file: "5"


    cygnus:
        container_name: cygnus
        hostname: cygnus
        restart: always
        image: fiware/cygnus-ngsi:latest
        ports:
            - "5050:5050"
            - "5080:5080"
        depends_on:
            - mysql-db
            - orion
        networks:
            - frontend
            - db
        environment:
            - "CYGNUS_MYSQL_HOST=mysql-db" # Hostname of the MySQL server used to persist historical context data 
            - "CYGNUS_MYSQL_PORT=3306"     # Port that the MySQL server uses to listen to commands
            - "CYGNUS_MYSQL_USER=root"     # Username for the MySQL database user
            - "CYGNUS_MYSQL_PASS=123"      # Password for the MySQL database user
            - "CYGNUS_SERVICE_PORT=5050"   # Notification Port that Cygnus listens when subcribing to context data changes
            - "CYGNUS_API_PORT=5080"       # Port that Cygnus listens on for operational reasons
        logging:
            options:
                max-size: "100m"
                max-file: "5"

    # Provide Historical DB management using Quantum Leap and Crate
    crate-db:
        container_name: db-crate
        hostname: crate-db
        restart: always
        image: crate:1.0.5
        ports:
            # Admin UI
            - "4200:4200"
            # Transport protocol
            - "4300:4300"
        networks:
            - frontend
            - db
        command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
        volumes:
            - ./crate-db:/data
        logging:
            options:
                max-size: "100m"
                max-file: "5"

    quantum-leap:
        container_name: fiware-quantum-leap
        hostname: quantum-leap
        restart: always
        image: smartsdk/quantumleap
        ports:
            - "8668:8668"
        networks:
            - frontend
            - db
        depends_on:
            - crate-db
        environment:
            - CRATE_HOST=crate-db
        logging:
            options:
                max-size: "100m"
                max-file: "5"
